### ISSUE TITLE
Add vault approle support

### ISSUE THREAD

**Issue by Joibel** [crumbhole/argocd-vault-replacer#45]
https://github.com/crumbhole/argocd-lovely-plugin/issues/37 requests approle support for vault.

**Comment by Joibel** [comment]
This should still be done, and is in progress.

**Comment by tico24** [comment]
Poke stalebot

**Comment by Joibel** [comment]
Poke stalebot

**Comment by remyj38** [comment]
@Joibel Do you have any news about this feature ?

**Comment by Joibel** [comment]
Humm, no. I know I started on it, but never finished. What is your usecase? Is vault running outside k8s?
