### ISSUE TITLE
json2htaccess is unstable (gives different results each time it is run)

### ISSUE THREAD

**Issue by Joibel** [crumbhole/argocd-vault-replacer#6]
htaccess uses bcrypt. bcrypt uses a salt, and the golang implementation randomises that salt for us with no control.

This means each time you run this it will give a different (correct and valid) result, but argo won't know this and will redeploy the relevant change. Repeatedly.

Providing a stable salt would fix this, but I'm not sure where to get this from, and the bcrypt library would need to allow this.

**Comment by Joibel** [comment]
It would still be worth tackling

**Comment by tico24** [comment]
Still an issue

**Comment by Joibel** [comment]
This would require a stable salt.
Golang bcrypt doens't expose a way to set the salt, because that's bad for security, the salt is supposed to be unknown for security.
We could find an alternative way to do this, but we still need a stable but unknown salt.
